# Generated by Django 3.2.20 on 2023-10-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20231003_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_edit_own_article', 'Peut éditer ses propres articles')]},
        ),
    ]
